server:
  port: 8181
spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: jrtp
    url: jdbc:h2:mem:testdb
    username: jrtp
  jpa:
    properties:
      hibernate:
        show-sql: true
        defer-datasource-initialization: true
  mail:
    host: smtp.gmail.com  
    port: 587
    username: luckynaveen149@gmail.com
    password: 9703961990n
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
